In [82]:
import pandas as pd
import numpy as np
import os
import json
import keras

In [83]:
data_path = r'../data/1/previous_heats_with_properties.json'

with open(data_path, 'r') as datafile:
    data = json.load(datafile)
df = pd.DataFrame(data)
df.head(10)

,actual_recipe,chemistry,heat_id,heat_seq,required_weight,steel_grade,tap_weight
0,"{'bushling': 300, 'pig_iron': 200, 'municipal_...",{'cu_pct': 0.095},heat-501,51,1000,ST1,970
1,"{'bushling': 300, 'pig_iron': 200, 'municipal_...",{'cu_pct': 0.104},heat-502,51,1000,ST1,920
2,"{'bushling': 300, 'pig_iron': 200, 'municipal_...",{'cu_pct': 0.105},heat-503,51,1000,ST1,940
3,"{'bushling': 300, 'pig_iron': 200, 'municipal_...",{'cu_pct': 0.089},heat-504,51,1000,ST1,935
4,"{'bushling': 300, 'pig_iron': 200, 'municipal_...",{'cu_pct': 0.093},heat-505,51,1000,ST1,945
5,"{'bushling': 275, 'pig_iron': 200, 'municipal_...",{'cu_pct': 0.102},heat-506,52,1200,ST2,910
6,"{'bushling': 275, 'pig_iron': 200, 'municipal_...",{'cu_pct': 0.114},heat-507,52,1200,ST2,930
7,"{'bushling': 250, 'pig_iron': 200, 'municipal_...",{'cu_pct': 0.118},heat-508,52,1200,ST2,965
8,"{'bushling': 250, 'pig_iron': 200, 'municipal_...",{'cu_pct': 0.124},heat-509,52,1200,ST2,940
9,"{'bushling': 250, 'pig_iron': 200, 'municipal_...",{'cu_pct': 0.121},heat-510,52,1200,ST2,975

In [84]:
df_1 = df.actual_recipe
df_2 = df.chemistry
print(df_1)

0     {'bushling': 300, 'pig_iron': 200, 'municipal_...
1     {'bushling': 300, 'pig_iron': 200, 'municipal_...
2     {'bushling': 300, 'pig_iron': 200, 'municipal_...
3     {'bushling': 300, 'pig_iron': 200, 'municipal_...
4     {'bushling': 300, 'pig_iron': 200, 'municipal_...
5     {'bushling': 275, 'pig_iron': 200, 'municipal_...
6     {'bushling': 275, 'pig_iron': 200, 'municipal_...
7     {'bushling': 250, 'pig_iron': 200, 'municipal_...
8     {'bushling': 250, 'pig_iron': 200, 'municipal_...
9     {'bushling': 250, 'pig_iron': 200, 'municipal_...
10    {'bushling': 250, 'pig_iron': 200, 'municipal_...
11    {'bushling': 200, 'pig_iron': 200, 'municipal_...
12    {'bushling': 200, 'pig_iron': 200, 'municipal_...
13    {'bushling': 200, 'pig_iron': 200, 'municipal_...
14    {'bushling': 200, 'pig_iron': 200, 'municipal_...
Name: actual_recipe, dtype: object

In [85]:
ls_1 = list(df_1)
ls_sg = list(df_2)
df_rec = pd.DataFrame.from_dict(ls_1)
df_sg = pd.DataFrame.from_dict(ls_sg)

In [65]:
print(df_sg)

    cu_pct
0    0.095
1    0.104
2    0.105
3    0.089
4    0.093
5    0.102
6    0.114
7    0.118
8    0.124
9    0.121
10   0.115
11   0.127
12   0.133
13   0.140
14   0.138

In [86]:
df.drop(columns=['heat_id', 'heat_seq', 'required_weight', 'tap_weight', 'actual_recipe', 'chemistry',], inplace=True)
df.head(10)

  steel_grade
0         ST1
1         ST1
2         ST1
3         ST1
4         ST1
5         ST2
6         ST2
7         ST2
8         ST2
9         ST2

In [87]:
merged_df = pd.concat([df, df_rec, df_sg], axis=1)
merged_df.replace('ST1', 1, inplace=True)
merged_df.replace('ST2', 2, inplace=True)
merged_df.replace('ST3', 3, inplace=True)

In [88]:
merged_df.head(20)

    steel_grade  bushling  municipal_shred  pig_iron  skulls  cu_pct
0             1       300              350       200     200   0.095
1             1       300              300       200     250   0.104
2             1       300              300       200     250   0.105
3             1       300              350       200     200   0.089
4             1       300              350       200     200   0.093
5             2       275              350       200     225   0.102
6             2       275              350       200     225   0.114
7             2       250              350       200     250   0.118
8             2       250              350       200     250   0.124
9             2       250              350       200     250   0.121
10            2       250              350       200     250   0.115
11            3       200              400       200     250   0.127
12            3       200              400       200     250   0.133
13            3       200              400       200     250   0.140
14            3       200              400       200     250   0.138

In [90]:

np_arr = merged_df.to_numpy()
x = np_arr[::,:-1]
y = np_arr[::,-1]

x_train = x[:-2]
y_train = y[:-2]

x_test = x[-2:]
y_test = y[-2:]
print(x_test)
print(y_test)

[[  3. 200. 400. 200. 250.]
 [  3. 200. 400. 200. 250.]]
[0.14  0.138]

In [99]:
import statsmodels.api as sm
model = sm.OLS(y_train, x_train).fit()
print_model = model.summary()
print(print_model)

                            OLS Regression Results
==============================================================================
Dep. Variable:                      y   R-squared:                       0.929
Model:                            OLS   Adj. R-squared:                  0.905
Method:                 Least Squares   F-statistic:                     39.22
Date:                Tue, 19 Nov 2019   Prob (F-statistic):           1.71e-05
Time:                        15:12:35   Log-Likelihood:                 54.866
No. Observations:                  13   AIC:                            -101.7
Df Residuals:                       9   BIC:                            -99.47
Df Model:                           3
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
x1             0.0053      0.007      0.790      0.450      -0.010       0.020
x2         -7.538e-05   8.01e-05     -0.941      0.371      -0.000       0.000
x3          7.379e-05   6.49e-05      1.137      0.285   -7.31e-05       0.000
const       7.954e-05   6.99e-06     11.383      0.000    6.37e-05    9.53e-05
x4             0.0003   6.38e-05      5.327      0.000       0.000       0.000
==============================================================================
Omnibus:                        0.468   Durbin-Watson:                   2.370
Prob(Omnibus):                  0.792   Jarque-Bera (JB):                0.523
Skew:                           0.123   Prob(JB):                        0.770
Kurtosis:                       2.049   Cond. No.                     4.06e+16
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 2.27e-27. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.

In [101]:
predictions = model.predict(x_test)
    
print(predictions)

[0.131125 0.131125]